// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: internal/exportformat/export.proto

package exportformat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KindType int32

const (
	KindType_KIND_TYPE_UNSPECIFIED KindType = 0
	KindType_ONE_KIND              KindType = 1
	KindType_ALL_KINDS             KindType = 2
)

// Enum value maps for KindType.
var (
	KindType_name = map[int32]string{
		0: "KIND_TYPE_UNSPECIFIED",
		1: "ONE_KIND",
		2: "ALL_KINDS",
	}
	KindType_value = map[string]int32{
		"KIND_TYPE_UNSPECIFIED": 0,
		"ONE_KIND":              1,
		"ALL_KINDS":             2,
	}
)

func (x KindType) Enum() *KindType {
	p := new(KindType)
	*p = x
	return p
}

func (x KindType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KindType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_exportformat_export_proto_enumTypes[0].Descriptor()
}

func (KindType) Type() protoreflect.EnumType {
	return &file_internal_exportformat_export_proto_enumTypes[0]
}

func (x KindType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *KindType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = KindType(num)
	return nil
}

// Deprecated: Use KindType.Descriptor instead.
func (KindType) EnumDescriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{0}
}

type NamespaceType int32

const (
	NamespaceType_NAMESPACE_TYPE_UNSPECIFIED NamespaceType = 0
	NamespaceType_DEFAULT_NAMESPACE          NamespaceType = 1
	NamespaceType_ONE_NAMESPACE              NamespaceType = 2
	NamespaceType_ALL_NAMESPACES             NamespaceType = 3
)

// Enum value maps for NamespaceType.
var (
	NamespaceType_name = map[int32]string{
		0: "NAMESPACE_TYPE_UNSPECIFIED",
		1: "DEFAULT_NAMESPACE",
		2: "ONE_NAMESPACE",
		3: "ALL_NAMESPACES",
	}
	NamespaceType_value = map[string]int32{
		"NAMESPACE_TYPE_UNSPECIFIED": 0,
		"DEFAULT_NAMESPACE":          1,
		"ONE_NAMESPACE":              2,
		"ALL_NAMESPACES":             3,
	}
)

func (x NamespaceType) Enum() *NamespaceType {
	p := new(NamespaceType)
	*p = x
	return p
}

func (x NamespaceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NamespaceType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_exportformat_export_proto_enumTypes[1].Descriptor()
}

func (NamespaceType) Type() protoreflect.EnumType {
	return &file_internal_exportformat_export_proto_enumTypes[1]
}

func (x NamespaceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *NamespaceType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = NamespaceType(num)
	return nil
}

// Deprecated: Use NamespaceType.Descriptor instead.
func (NamespaceType) EnumDescriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{1}
}

type Property_Meaning int32

const (
	Property_NO_MEANING                       Property_Meaning = 0
	Property_ATOM_CATEGORY                    Property_Meaning = 1
	Property_ATOM_LINK                        Property_Meaning = 2
	Property_ATOM_TITLE                       Property_Meaning = 3
	Property_ATOM_CONTENT                     Property_Meaning = 4
	Property_ATOM_SUMMARY                     Property_Meaning = 5
	Property_ATOM_AUTHOR                      Property_Meaning = 6
	Property_GD_WHEN                          Property_Meaning = 7
	Property_GD_EMAIL                         Property_Meaning = 8
	Property_GEORSS_POINT                     Property_Meaning = 9
	Property_GD_IM                            Property_Meaning = 10
	Property_GD_PHONENUMBER                   Property_Meaning = 11
	Property_GD_POSTALADDRESS                 Property_Meaning = 12
	Property_GD_RATING                        Property_Meaning = 13
	Property_BLOB                             Property_Meaning = 14
	Property_TEXT                             Property_Meaning = 15
	Property_BYTESTRING                       Property_Meaning = 16
	Property_BLOBKEY                          Property_Meaning = 17
	Property_INDEX_VALUE                      Property_Meaning = 18
	Property_ENTITY_PROTO                     Property_Meaning = 19
	Property_EMPTY_LIST                       Property_Meaning = 24
	Property_LEGACY_FORMAT_VECTOR             Property_Meaning = 31
	Property_LEGACY_FORMAT_DECIMAL128         Property_Meaning = 32
	Property_LEGACY_FORMAT_BYTES_WITH_SUBTYPE Property_Meaning = 33
	Property_LEGACY_FORMAT_OBJECT_ID          Property_Meaning = 34
	Property_LEGACY_FORMAT_REGEX              Property_Meaning = 35
	Property_LEGACY_FORMAT_INT32              Property_Meaning = 36
	Property_LEGACY_FORMAT_REQUEST_TIMESTAMP  Property_Meaning = 37
	Property_LEGACY_FORMAT_MIN_VALUE          Property_Meaning = 38
	Property_LEGACY_FORMAT_MAX_VALUE          Property_Meaning = 39
	Property_LEGACY_FORMAT_NESTED_ARRAY       Property_Meaning = 40
)

// Enum value maps for Property_Meaning.
var (
	Property_Meaning_name = map[int32]string{
		0:  "NO_MEANING",
		1:  "ATOM_CATEGORY",
		2:  "ATOM_LINK",
		3:  "ATOM_TITLE",
		4:  "ATOM_CONTENT",
		5:  "ATOM_SUMMARY",
		6:  "ATOM_AUTHOR",
		7:  "GD_WHEN",
		8:  "GD_EMAIL",
		9:  "GEORSS_POINT",
		10: "GD_IM",
		11: "GD_PHONENUMBER",
		12: "GD_POSTALADDRESS",
		13: "GD_RATING",
		14: "BLOB",
		15: "TEXT",
		16: "BYTESTRING",
		17: "BLOBKEY",
		18: "INDEX_VALUE",
		19: "ENTITY_PROTO",
		24: "EMPTY_LIST",
		31: "LEGACY_FORMAT_VECTOR",
		32: "LEGACY_FORMAT_DECIMAL128",
		33: "LEGACY_FORMAT_BYTES_WITH_SUBTYPE",
		34: "LEGACY_FORMAT_OBJECT_ID",
		35: "LEGACY_FORMAT_REGEX",
		36: "LEGACY_FORMAT_INT32",
		37: "LEGACY_FORMAT_REQUEST_TIMESTAMP",
		38: "LEGACY_FORMAT_MIN_VALUE",
		39: "LEGACY_FORMAT_MAX_VALUE",
		40: "LEGACY_FORMAT_NESTED_ARRAY",
	}
	Property_Meaning_value = map[string]int32{
		"NO_MEANING":                       0,
		"ATOM_CATEGORY":                    1,
		"ATOM_LINK":                        2,
		"ATOM_TITLE":                       3,
		"ATOM_CONTENT":                     4,
		"ATOM_SUMMARY":                     5,
		"ATOM_AUTHOR":                      6,
		"GD_WHEN":                          7,
		"GD_EMAIL":                         8,
		"GEORSS_POINT":                     9,
		"GD_IM":                            10,
		"GD_PHONENUMBER":                   11,
		"GD_POSTALADDRESS":                 12,
		"GD_RATING":                        13,
		"BLOB":                             14,
		"TEXT":                             15,
		"BYTESTRING":                       16,
		"BLOBKEY":                          17,
		"INDEX_VALUE":                      18,
		"ENTITY_PROTO":                     19,
		"EMPTY_LIST":                       24,
		"LEGACY_FORMAT_VECTOR":             31,
		"LEGACY_FORMAT_DECIMAL128":         32,
		"LEGACY_FORMAT_BYTES_WITH_SUBTYPE": 33,
		"LEGACY_FORMAT_OBJECT_ID":          34,
		"LEGACY_FORMAT_REGEX":              35,
		"LEGACY_FORMAT_INT32":              36,
		"LEGACY_FORMAT_REQUEST_TIMESTAMP":  37,
		"LEGACY_FORMAT_MIN_VALUE":          38,
		"LEGACY_FORMAT_MAX_VALUE":          39,
		"LEGACY_FORMAT_NESTED_ARRAY":       40,
	}
)

func (x Property_Meaning) Enum() *Property_Meaning {
	p := new(Property_Meaning)
	*p = x
	return p
}

func (x Property_Meaning) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Property_Meaning) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_exportformat_export_proto_enumTypes[2].Descriptor()
}

func (Property_Meaning) Type() protoreflect.EnumType {
	return &file_internal_exportformat_export_proto_enumTypes[2]
}

func (x Property_Meaning) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Property_Meaning) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Property_Meaning(num)
	return nil
}

// Deprecated: Use Property_Meaning.Descriptor instead.
func (Property_Meaning) EnumDescriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{1, 0}
}

// The entity messages retain the wire numbers of App Engine's datastore_v3.proto.
type PropertyValue struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	Int64Value     *int64                        `protobuf:"varint,1,opt,name=int64_value,json=int64Value" json:"int64_value,omitempty"`
	BooleanValue   *bool                         `protobuf:"varint,2,opt,name=boolean_value,json=booleanValue" json:"boolean_value,omitempty"`
	StringValue    *string                       `protobuf:"bytes,3,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	DoubleValue    *float64                      `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	Pointvalue     *PropertyValue_PointValue     `protobuf:"group,5,opt,name=PointValue,json=pointvalue" json:"pointvalue,omitempty"`
	Uservalue      *PropertyValue_UserValue      `protobuf:"group,8,opt,name=UserValue,json=uservalue" json:"uservalue,omitempty"`
	Referencevalue *PropertyValue_ReferenceValue `protobuf:"group,12,opt,name=ReferenceValue,json=referencevalue" json:"referencevalue,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PropertyValue) Reset() {
	*x = PropertyValue{}
	mi := &file_internal_exportformat_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyValue) ProtoMessage() {}

func (x *PropertyValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyValue.ProtoReflect.Descriptor instead.
func (*PropertyValue) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{0}
}

func (x *PropertyValue) GetInt64Value() int64 {
	if x != nil && x.Int64Value != nil {
		return *x.Int64Value
	}
	return 0
}

func (x *PropertyValue) GetBooleanValue() bool {
	if x != nil && x.BooleanValue != nil {
		return *x.BooleanValue
	}
	return false
}

func (x *PropertyValue) GetStringValue() string {
	if x != nil && x.StringValue != nil {
		return *x.StringValue
	}
	return ""
}

func (x *PropertyValue) GetDoubleValue() float64 {
	if x != nil && x.DoubleValue != nil {
		return *x.DoubleValue
	}
	return 0
}

func (x *PropertyValue) GetPointvalue() *PropertyValue_PointValue {
	if x != nil {
		return x.Pointvalue
	}
	return nil
}

func (x *PropertyValue) GetUservalue() *PropertyValue_UserValue {
	if x != nil {
		return x.Uservalue
	}
	return nil
}

func (x *PropertyValue) GetReferencevalue() *PropertyValue_ReferenceValue {
	if x != nil {
		return x.Referencevalue
	}
	return nil
}

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meaning       *Property_Meaning      `protobuf:"varint,1,opt,name=meaning,enum=hearthstore.exportformat.Property_Meaning,def=0" json:"meaning,omitempty"`
	MeaningUri    *string                `protobuf:"bytes,2,opt,name=meaning_uri,json=meaningUri" json:"meaning_uri,omitempty"`
	Name          *string                `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Multiple      *bool                  `protobuf:"varint,4,req,name=multiple" json:"multiple,omitempty"`
	Value         *PropertyValue         `protobuf:"bytes,5,req,name=value" json:"value,omitempty"`
	Searchable    *bool                  `protobuf:"varint,6,opt,name=searchable,def=0" json:"searchable,omitempty"`
	Locale        *string                `protobuf:"bytes,9,opt,name=locale,def=en" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Property fields.
const (
	Default_Property_Meaning    = Property_NO_MEANING
	Default_Property_Searchable = bool(false)
	Default_Property_Locale     = string("en")
)

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_internal_exportformat_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{1}
}

func (x *Property) GetMeaning() Property_Meaning {
	if x != nil && x.Meaning != nil {
		return *x.Meaning
	}
	return Default_Property_Meaning
}

func (x *Property) GetMeaningUri() string {
	if x != nil && x.MeaningUri != nil {
		return *x.MeaningUri
	}
	return ""
}

func (x *Property) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Property) GetMultiple() bool {
	if x != nil && x.Multiple != nil {
		return *x.Multiple
	}
	return false
}

func (x *Property) GetValue() *PropertyValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Property) GetSearchable() bool {
	if x != nil && x.Searchable != nil {
		return *x.Searchable
	}
	return Default_Property_Searchable
}

func (x *Property) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return Default_Property_Locale
}

type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Element       []*Path_Element        `protobuf:"group,1,rep,name=Element,json=element" json:"element,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_internal_exportformat_export_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{2}
}

func (x *Path) GetElement() []*Path_Element {
	if x != nil {
		return x.Element
	}
	return nil
}

type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *string                `protobuf:"bytes,13,req,name=app" json:"app,omitempty"`
	Path          *Path                  `protobuf:"bytes,14,req,name=path" json:"path,omitempty"`
	NameSpace     *string                `protobuf:"bytes,20,opt,name=name_space,json=nameSpace" json:"name_space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_internal_exportformat_export_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{3}
}

func (x *Reference) GetApp() string {
	if x != nil && x.App != nil {
		return *x.App
	}
	return ""
}

func (x *Reference) GetPath() *Path {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Reference) GetNameSpace() string {
	if x != nil && x.NameSpace != nil {
		return *x.NameSpace
	}
	return ""
}

type EntityProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Reference             `protobuf:"bytes,13,req,name=key" json:"key,omitempty"`
	Property      []*Property            `protobuf:"bytes,14,rep,name=property" json:"property,omitempty"`
	RawProperty   []*Property            `protobuf:"bytes,15,rep,name=raw_property,json=rawProperty" json:"raw_property,omitempty"`
	EntityGroup   *Path                  `protobuf:"bytes,16,req,name=entity_group,json=entityGroup" json:"entity_group,omitempty"`
	Rank          *int32                 `protobuf:"varint,18,opt,name=rank" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityProto) Reset() {
	*x = EntityProto{}
	mi := &file_internal_exportformat_export_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityProto) ProtoMessage() {}

func (x *EntityProto) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityProto.ProtoReflect.Descriptor instead.
func (*EntityProto) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{4}
}

func (x *EntityProto) GetKey() *Reference {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *EntityProto) GetProperty() []*Property {
	if x != nil {
		return x.Property
	}
	return nil
}

func (x *EntityProto) GetRawProperty() []*Property {
	if x != nil {
		return x.RawProperty
	}
	return nil
}

func (x *EntityProto) GetEntityGroup() *Path {
	if x != nil {
		return x.EntityGroup
	}
	return nil
}

func (x *EntityProto) GetRank() int32 {
	if x != nil && x.Rank != nil {
		return *x.Rank
	}
	return 0
}

type EntitySetSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KindType      *KindType              `protobuf:"varint,1,opt,name=kind_type,json=kindType,enum=hearthstore.exportformat.KindType" json:"kind_type,omitempty"`
	Kind          *string                `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	NamespaceType *NamespaceType         `protobuf:"varint,3,opt,name=namespace_type,json=namespaceType,enum=hearthstore.exportformat.NamespaceType" json:"namespace_type,omitempty"`
	Namespace     *string                `protobuf:"bytes,4,opt,name=namespace" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySetSpec) Reset() {
	*x = EntitySetSpec{}
	mi := &file_internal_exportformat_export_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySetSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySetSpec) ProtoMessage() {}

func (x *EntitySetSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySetSpec.ProtoReflect.Descriptor instead.
func (*EntitySetSpec) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{5}
}

func (x *EntitySetSpec) GetKindType() KindType {
	if x != nil && x.KindType != nil {
		return *x.KindType
	}
	return KindType_KIND_TYPE_UNSPECIFIED
}

func (x *EntitySetSpec) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *EntitySetSpec) GetNamespaceType() NamespaceType {
	if x != nil && x.NamespaceType != nil {
		return *x.NamespaceType
	}
	return NamespaceType_NAMESPACE_TYPE_UNSPECIFIED
}

func (x *EntitySetSpec) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type SingleExportMetadataPointer struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EntitySetSpec      *EntitySetSpec         `protobuf:"bytes,1,opt,name=entity_set_spec,json=entitySetSpec" json:"entity_set_spec,omitempty"`
	ExportMetadataFile *string                `protobuf:"bytes,2,opt,name=export_metadata_file,json=exportMetadataFile" json:"export_metadata_file,omitempty"`
	NumEntities        *int64                 `protobuf:"varint,3,opt,name=num_entities,json=numEntities" json:"num_entities,omitempty"`
	NumBytes           *int64                 `protobuf:"varint,4,opt,name=num_bytes,json=numBytes" json:"num_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SingleExportMetadataPointer) Reset() {
	*x = SingleExportMetadataPointer{}
	mi := &file_internal_exportformat_export_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleExportMetadataPointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleExportMetadataPointer) ProtoMessage() {}

func (x *SingleExportMetadataPointer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleExportMetadataPointer.ProtoReflect.Descriptor instead.
func (*SingleExportMetadataPointer) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{6}
}

func (x *SingleExportMetadataPointer) GetEntitySetSpec() *EntitySetSpec {
	if x != nil {
		return x.EntitySetSpec
	}
	return nil
}

func (x *SingleExportMetadataPointer) GetExportMetadataFile() string {
	if x != nil && x.ExportMetadataFile != nil {
		return *x.ExportMetadataFile
	}
	return ""
}

func (x *SingleExportMetadataPointer) GetNumEntities() int64 {
	if x != nil && x.NumEntities != nil {
		return *x.NumEntities
	}
	return 0
}

func (x *SingleExportMetadataPointer) GetNumBytes() int64 {
	if x != nil && x.NumBytes != nil {
		return *x.NumBytes
	}
	return 0
}

type OverallExportMetadata struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	EntitySet     []*SingleExportMetadataPointer `protobuf:"bytes,1,rep,name=entity_set,json=entitySet" json:"entity_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverallExportMetadata) Reset() {
	*x = OverallExportMetadata{}
	mi := &file_internal_exportformat_export_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverallExportMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverallExportMetadata) ProtoMessage() {}

func (x *OverallExportMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverallExportMetadata.ProtoReflect.Descriptor instead.
func (*OverallExportMetadata) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{7}
}

func (x *OverallExportMetadata) GetEntitySet() []*SingleExportMetadataPointer {
	if x != nil {
		return x.EntitySet
	}
	return nil
}

type BackupInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BackupName     *string                `protobuf:"bytes,1,opt,name=backup_name,json=backupName" json:"backup_name,omitempty"`
	StartTimestamp *int64                 `protobuf:"varint,2,opt,name=start_timestamp,json=startTimestamp" json:"start_timestamp,omitempty"`
	EndTimestamp   *int64                 `protobuf:"varint,3,opt,name=end_timestamp,json=endTimestamp" json:"end_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackupInfo) Reset() {
	*x = BackupInfo{}
	mi := &file_internal_exportformat_export_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupInfo) ProtoMessage() {}

func (x *BackupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupInfo.ProtoReflect.Descriptor instead.
func (*BackupInfo) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{8}
}

func (x *BackupInfo) GetBackupName() string {
	if x != nil && x.BackupName != nil {
		return *x.BackupName
	}
	return ""
}

func (x *BackupInfo) GetStartTimestamp() int64 {
	if x != nil && x.StartTimestamp != nil {
		return *x.StartTimestamp
	}
	return 0
}

func (x *BackupInfo) GetEndTimestamp() int64 {
	if x != nil && x.EndTimestamp != nil {
		return *x.EndTimestamp
	}
	return 0
}

type KindBackupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          *string                `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	File          []string               `protobuf:"bytes,2,rep,name=file" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindBackupInfo) Reset() {
	*x = KindBackupInfo{}
	mi := &file_internal_exportformat_export_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindBackupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindBackupInfo) ProtoMessage() {}

func (x *KindBackupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindBackupInfo.ProtoReflect.Descriptor instead.
func (*KindBackupInfo) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{9}
}

func (x *KindBackupInfo) GetKind() string {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return ""
}

func (x *KindBackupInfo) GetFile() []string {
	if x != nil {
		return x.File
	}
	return nil
}

type Backup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupInfo    *BackupInfo            `protobuf:"bytes,1,opt,name=backup_info,json=backupInfo" json:"backup_info,omitempty"`
	Kind          []*KindBackupInfo      `protobuf:"bytes,2,rep,name=kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backup) Reset() {
	*x = Backup{}
	mi := &file_internal_exportformat_export_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backup) ProtoMessage() {}

func (x *Backup) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backup.ProtoReflect.Descriptor instead.
func (*Backup) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{10}
}

func (x *Backup) GetBackupInfo() *BackupInfo {
	if x != nil {
		return x.BackupInfo
	}
	return nil
}

func (x *Backup) GetKind() []*KindBackupInfo {
	if x != nil {
		return x.Kind
	}
	return nil
}

type PropertyValue_PointValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float64               `protobuf:"fixed64,6,req,name=x" json:"x,omitempty"`
	Y             *float64               `protobuf:"fixed64,7,req,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyValue_PointValue) Reset() {
	*x = PropertyValue_PointValue{}
	mi := &file_internal_exportformat_export_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyValue_PointValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyValue_PointValue) ProtoMessage() {}

func (x *PropertyValue_PointValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyValue_PointValue.ProtoReflect.Descriptor instead.
func (*PropertyValue_PointValue) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PropertyValue_PointValue) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *PropertyValue_PointValue) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type PropertyValue_UserValue struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Email             *string                `protobuf:"bytes,9,req,name=email" json:"email,omitempty"`
	AuthDomain        *string                `protobuf:"bytes,10,req,name=auth_domain,json=authDomain" json:"auth_domain,omitempty"`
	Nickname          *string                `protobuf:"bytes,11,opt,name=nickname" json:"nickname,omitempty"`
	FederatedIdentity *string                `protobuf:"bytes,21,opt,name=federated_identity,json=federatedIdentity" json:"federated_identity,omitempty"`
	FederatedProvider *string                `protobuf:"bytes,22,opt,name=federated_provider,json=federatedProvider" json:"federated_provider,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PropertyValue_UserValue) Reset() {
	*x = PropertyValue_UserValue{}
	mi := &file_internal_exportformat_export_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyValue_UserValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyValue_UserValue) ProtoMessage() {}

func (x *PropertyValue_UserValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyValue_UserValue.ProtoReflect.Descriptor instead.
func (*PropertyValue_UserValue) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PropertyValue_UserValue) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *PropertyValue_UserValue) GetAuthDomain() string {
	if x != nil && x.AuthDomain != nil {
		return *x.AuthDomain
	}
	return ""
}

func (x *PropertyValue_UserValue) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *PropertyValue_UserValue) GetFederatedIdentity() string {
	if x != nil && x.FederatedIdentity != nil {
		return *x.FederatedIdentity
	}
	return ""
}

func (x *PropertyValue_UserValue) GetFederatedProvider() string {
	if x != nil && x.FederatedProvider != nil {
		return *x.FederatedProvider
	}
	return ""
}

type PropertyValue_ReferenceValue struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	App           *string                                     `protobuf:"bytes,13,req,name=app" json:"app,omitempty"`
	NameSpace     *string                                     `protobuf:"bytes,20,opt,name=name_space,json=nameSpace" json:"name_space,omitempty"`
	Pathelement   []*PropertyValue_ReferenceValue_PathElement `protobuf:"group,14,rep,name=PathElement,json=pathelement" json:"pathelement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyValue_ReferenceValue) Reset() {
	*x = PropertyValue_ReferenceValue{}
	mi := &file_internal_exportformat_export_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyValue_ReferenceValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyValue_ReferenceValue) ProtoMessage() {}

func (x *PropertyValue_ReferenceValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyValue_ReferenceValue.ProtoReflect.Descriptor instead.
func (*PropertyValue_ReferenceValue) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{0, 2}
}

func (x *PropertyValue_ReferenceValue) GetApp() string {
	if x != nil && x.App != nil {
		return *x.App
	}
	return ""
}

func (x *PropertyValue_ReferenceValue) GetNameSpace() string {
	if x != nil && x.NameSpace != nil {
		return *x.NameSpace
	}
	return ""
}

func (x *PropertyValue_ReferenceValue) GetPathelement() []*PropertyValue_ReferenceValue_PathElement {
	if x != nil {
		return x.Pathelement
	}
	return nil
}

type PropertyValue_ReferenceValue_PathElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,15,req,name=type" json:"type,omitempty"`
	Id            *int64                 `protobuf:"varint,16,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,17,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyValue_ReferenceValue_PathElement) Reset() {
	*x = PropertyValue_ReferenceValue_PathElement{}
	mi := &file_internal_exportformat_export_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyValue_ReferenceValue_PathElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyValue_ReferenceValue_PathElement) ProtoMessage() {}

func (x *PropertyValue_ReferenceValue_PathElement) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyValue_ReferenceValue_PathElement.ProtoReflect.Descriptor instead.
func (*PropertyValue_ReferenceValue_PathElement) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *PropertyValue_ReferenceValue_PathElement) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *PropertyValue_ReferenceValue_PathElement) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PropertyValue_ReferenceValue_PathElement) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type Path_Element struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,2,req,name=type" json:"type,omitempty"`
	Id            *int64                 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path_Element) Reset() {
	*x = Path_Element{}
	mi := &file_internal_exportformat_export_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path_Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path_Element) ProtoMessage() {}

func (x *Path_Element) ProtoReflect() protoreflect.Message {
	mi := &file_internal_exportformat_export_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path_Element.ProtoReflect.Descriptor instead.
func (*Path_Element) Descriptor() ([]byte, []int) {
	return file_internal_exportformat_export_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Path_Element) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *Path_Element) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Path_Element) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_internal_exportformat_export_proto protoreflect.FileDescriptor

const file_internal_exportformat_export_proto_rawDesc = "" +
	"\n" +
	"\"internal/exportformat/export.proto\x12\x18hearthstore.exportformat\"\xfa\x06\n" +
	"\rPropertyValue\x12\x1f\n" +
	"\vint64_value\x18\x01 \x01(\x03R\n" +
	"int64Value\x12#\n" +
	"\rboolean_value\x18\x02 \x01(\bR\fbooleanValue\x12!\n" +
	"\fstring_value\x18\x03 \x01(\tR\vstringValue\x12!\n" +
	"\fdouble_value\x18\x04 \x01(\x01R\vdoubleValue\x12R\n" +
	"\n" +
	"pointvalue\x18\x05 \x01(\n" +
	"22.hearthstore.exportformat.PropertyValue.PointValueR\n" +
	"pointvalue\x12O\n" +
	"\tuservalue\x18\b \x01(\n" +
	"21.hearthstore.exportformat.PropertyValue.UserValueR\tuservalue\x12^\n" +
	"\x0ereferencevalue\x18\f \x01(\n" +
	"26.hearthstore.exportformat.PropertyValue.ReferenceValueR\x0ereferencevalue\x1a(\n" +
	"\n" +
	"PointValue\x12\f\n" +
	"\x01x\x18\x06 \x02(\x01R\x01x\x12\f\n" +
	"\x01y\x18\a \x02(\x01R\x01y\x1a\xbc\x01\n" +
	"\tUserValue\x12\x14\n" +
	"\x05email\x18\t \x02(\tR\x05email\x12\x1f\n" +
	"\vauth_domain\x18\n" +
	" \x02(\tR\n" +
	"authDomain\x12\x1a\n" +
	"\bnickname\x18\v \x01(\tR\bnickname\x12-\n" +
	"\x12federated_identity\x18\x15 \x01(\tR\x11federatedIdentity\x12-\n" +
	"\x12federated_provider\x18\x16 \x01(\tR\x11federatedProvider\x1a\xee\x01\n" +
	"\x0eReferenceValue\x12\x10\n" +
	"\x03app\x18\r \x02(\tR\x03app\x12\x1d\n" +
	"\n" +
	"name_space\x18\x14 \x01(\tR\tnameSpace\x12d\n" +
	"\vpathelement\x18\x0e \x03(\n" +
	"2B.hearthstore.exportformat.PropertyValue.ReferenceValue.PathElementR\vpathelement\x1aE\n" +
	"\vPathElement\x12\x12\n" +
	"\x04type\x18\x0f \x02(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x10 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x11 \x01(\tR\x04name\"\xb3\a\n" +
	"\bProperty\x12P\n" +
	"\ameaning\x18\x01 \x01(\x0e2*.hearthstore.exportformat.Property.Meaning:\n" +
	"NO_MEANINGR\ameaning\x12\x1f\n" +
	"\vmeaning_uri\x18\x02 \x01(\tR\n" +
	"meaningUri\x12\x12\n" +
	"\x04name\x18\x03 \x02(\tR\x04name\x12\x1a\n" +
	"\bmultiple\x18\x04 \x02(\bR\bmultiple\x12=\n" +
	"\x05value\x18\x05 \x02(\v2'.hearthstore.exportformat.PropertyValueR\x05value\x12%\n" +
	"\n" +
	"searchable\x18\x06 \x01(\b:\x05falseR\n" +
	"searchable\x12\x1a\n" +
	"\x06locale\x18\t \x01(\t:\x02enR\x06locale\"\x81\x05\n" +
	"\aMeaning\x12\x0e\n" +
	"\n" +
	"NO_MEANING\x10\x00\x12\x11\n" +
	"\rATOM_CATEGORY\x10\x01\x12\r\n" +
	"\tATOM_LINK\x10\x02\x12\x0e\n" +
	"\n" +
	"ATOM_TITLE\x10\x03\x12\x10\n" +
	"\fATOM_CONTENT\x10\x04\x12\x10\n" +
	"\fATOM_SUMMARY\x10\x05\x12\x0f\n" +
	"\vATOM_AUTHOR\x10\x06\x12\v\n" +
	"\aGD_WHEN\x10\a\x12\f\n" +
	"\bGD_EMAIL\x10\b\x12\x10\n" +
	"\fGEORSS_POINT\x10\t\x12\t\n" +
	"\x05GD_IM\x10\n" +
	"\x12\x12\n" +
	"\x0eGD_PHONENUMBER\x10\v\x12\x14\n" +
	"\x10GD_POSTALADDRESS\x10\f\x12\r\n" +
	"\tGD_RATING\x10\r\x12\b\n" +
	"\x04BLOB\x10\x0e\x12\b\n" +
	"\x04TEXT\x10\x0f\x12\x0e\n" +
	"\n" +
	"BYTESTRING\x10\x10\x12\v\n" +
	"\aBLOBKEY\x10\x11\x12\x0f\n" +
	"\vINDEX_VALUE\x10\x12\x12\x10\n" +
	"\fENTITY_PROTO\x10\x13\x12\x0e\n" +
	"\n" +
	"EMPTY_LIST\x10\x18\x12\x18\n" +
	"\x14LEGACY_FORMAT_VECTOR\x10\x1f\x12\x1c\n" +
	"\x18LEGACY_FORMAT_DECIMAL128\x10 \x12$\n" +
	" LEGACY_FORMAT_BYTES_WITH_SUBTYPE\x10!\x12\x1b\n" +
	"\x17LEGACY_FORMAT_OBJECT_ID\x10\"\x12\x17\n" +
	"\x13LEGACY_FORMAT_REGEX\x10#\x12\x17\n" +
	"\x13LEGACY_FORMAT_INT32\x10$\x12#\n" +
	"\x1fLEGACY_FORMAT_REQUEST_TIMESTAMP\x10%\x12\x1b\n" +
	"\x17LEGACY_FORMAT_MIN_VALUE\x10&\x12\x1b\n" +
	"\x17LEGACY_FORMAT_MAX_VALUE\x10'\x12\x1e\n" +
	"\x1aLEGACY_FORMAT_NESTED_ARRAY\x10(\"\x8b\x01\n" +
	"\x04Path\x12@\n" +
	"\aelement\x18\x01 \x03(\n" +
	"2&.hearthstore.exportformat.Path.ElementR\aelement\x1aA\n" +
	"\aElement\x12\x12\n" +
	"\x04type\x18\x02 \x02(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"p\n" +
	"\tReference\x12\x10\n" +
	"\x03app\x18\r \x02(\tR\x03app\x122\n" +
	"\x04path\x18\x0e \x02(\v2\x1e.hearthstore.exportformat.PathR\x04path\x12\x1d\n" +
	"\n" +
	"name_space\x18\x14 \x01(\tR\tnameSpace\"\xa2\x02\n" +
	"\vEntityProto\x125\n" +
	"\x03key\x18\r \x02(\v2#.hearthstore.exportformat.ReferenceR\x03key\x12>\n" +
	"\bproperty\x18\x0e \x03(\v2\".hearthstore.exportformat.PropertyR\bproperty\x12E\n" +
	"\fraw_property\x18\x0f \x03(\v2\".hearthstore.exportformat.PropertyR\vrawProperty\x12A\n" +
	"\fentity_group\x18\x10 \x02(\v2\x1e.hearthstore.exportformat.PathR\ventityGroup\x12\x12\n" +
	"\x04rank\x18\x12 \x01(\x05R\x04rank\"\xd2\x01\n" +
	"\rEntitySetSpec\x12?\n" +
	"\tkind_type\x18\x01 \x01(\x0e2\".hearthstore.exportformat.KindTypeR\bkindType\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12N\n" +
	"\x0enamespace_type\x18\x03 \x01(\x0e2'.hearthstore.exportformat.NamespaceTypeR\rnamespaceType\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"\xe0\x01\n" +
	"\x1bSingleExportMetadataPointer\x12O\n" +
	"\x0fentity_set_spec\x18\x01 \x01(\v2'.hearthstore.exportformat.EntitySetSpecR\rentitySetSpec\x120\n" +
	"\x14export_metadata_file\x18\x02 \x01(\tR\x12exportMetadataFile\x12!\n" +
	"\fnum_entities\x18\x03 \x01(\x03R\vnumEntities\x12\x1b\n" +
	"\tnum_bytes\x18\x04 \x01(\x03R\bnumBytes\"m\n" +
	"\x15OverallExportMetadata\x12T\n" +
	"\n" +
	"entity_set\x18\x01 \x03(\v25.hearthstore.exportformat.SingleExportMetadataPointerR\tentitySet\"{\n" +
	"\n" +
	"BackupInfo\x12\x1f\n" +
	"\vbackup_name\x18\x01 \x01(\tR\n" +
	"backupName\x12'\n" +
	"\x0fstart_timestamp\x18\x02 \x01(\x03R\x0estartTimestamp\x12#\n" +
	"\rend_timestamp\x18\x03 \x01(\x03R\fendTimestamp\"8\n" +
	"\x0eKindBackupInfo\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04file\x18\x02 \x03(\tR\x04file\"\x8d\x01\n" +
	"\x06Backup\x12E\n" +
	"\vbackup_info\x18\x01 \x01(\v2$.hearthstore.exportformat.BackupInfoR\n" +
	"backupInfo\x12<\n" +
	"\x04kind\x18\x02 \x03(\v2(.hearthstore.exportformat.KindBackupInfoR\x04kind*B\n" +
	"\bKindType\x12\x19\n" +
	"\x15KIND_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bONE_KIND\x10\x01\x12\r\n" +
	"\tALL_KINDS\x10\x02*m\n" +
	"\rNamespaceType\x12\x1e\n" +
	"\x1aNAMESPACE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DEFAULT_NAMESPACE\x10\x01\x12\x11\n" +
	"\rONE_NAMESPACE\x10\x02\x12\x12\n" +
	"\x0eALL_NAMESPACES\x10\x03BMZKgithub.com/magnus-rattlehead/hearthstore/internal/exportformat;exportformat"

var (
	file_internal_exportformat_export_proto_rawDescOnce sync.Once
	file_internal_exportformat_export_proto_rawDescData []byte
)

func file_internal_exportformat_export_proto_rawDescGZIP() []byte {
	file_internal_exportformat_export_proto_rawDescOnce.Do(func() {
		file_internal_exportformat_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_exportformat_export_proto_rawDesc), len(file_internal_exportformat_export_proto_rawDesc)))
	})
	return file_internal_exportformat_export_proto_rawDescData
}

var file_internal_exportformat_export_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_exportformat_export_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_exportformat_export_proto_goTypes = []any{
	(KindType)(0),                                    // 0: hearthstore.exportformat.KindType
	(NamespaceType)(0),                               // 1: hearthstore.exportformat.NamespaceType
	(Property_Meaning)(0),                            // 2: hearthstore.exportformat.Property.Meaning
	(*PropertyValue)(nil),                            // 3: hearthstore.exportformat.PropertyValue
	(*Property)(nil),                                 // 4: hearthstore.exportformat.Property
	(*Path)(nil),                                     // 5: hearthstore.exportformat.Path
	(*Reference)(nil),                                // 6: hearthstore.exportformat.Reference
	(*EntityProto)(nil),                              // 7: hearthstore.exportformat.EntityProto
	(*EntitySetSpec)(nil),                            // 8: hearthstore.exportformat.EntitySetSpec
	(*SingleExportMetadataPointer)(nil),              // 9: hearthstore.exportformat.SingleExportMetadataPointer
	(*OverallExportMetadata)(nil),                    // 10: hearthstore.exportformat.OverallExportMetadata
	(*BackupInfo)(nil),                               // 11: hearthstore.exportformat.BackupInfo
	(*KindBackupInfo)(nil),                           // 12: hearthstore.exportformat.KindBackupInfo
	(*Backup)(nil),                                   // 13: hearthstore.exportformat.Backup
	(*PropertyValue_PointValue)(nil),                 // 14: hearthstore.exportformat.PropertyValue.PointValue
	(*PropertyValue_UserValue)(nil),                  // 15: hearthstore.exportformat.PropertyValue.UserValue
	(*PropertyValue_ReferenceValue)(nil),             // 16: hearthstore.exportformat.PropertyValue.ReferenceValue
	(*PropertyValue_ReferenceValue_PathElement)(nil), // 17: hearthstore.exportformat.PropertyValue.ReferenceValue.PathElement
	(*Path_Element)(nil),                             // 18: hearthstore.exportformat.Path.Element
}
var file_internal_exportformat_export_proto_depIdxs = []int32{
	14, // 0: hearthstore.exportformat.PropertyValue.pointvalue:type_name -> hearthstore.exportformat.PropertyValue.PointValue
	15, // 1: hearthstore.exportformat.PropertyValue.uservalue:type_name -> hearthstore.exportformat.PropertyValue.UserValue
	16, // 2: hearthstore.exportformat.PropertyValue.referencevalue:type_name -> hearthstore.exportformat.PropertyValue.ReferenceValue
	2,  // 3: hearthstore.exportformat.Property.meaning:type_name -> hearthstore.exportformat.Property.Meaning
	3,  // 4: hearthstore.exportformat.Property.value:type_name -> hearthstore.exportformat.PropertyValue
	18, // 5: hearthstore.exportformat.Path.element:type_name -> hearthstore.exportformat.Path.Element
	5,  // 6: hearthstore.exportformat.Reference.path:type_name -> hearthstore.exportformat.Path
	6,  // 7: hearthstore.exportformat.EntityProto.key:type_name -> hearthstore.exportformat.Reference
	4,  // 8: hearthstore.exportformat.EntityProto.property:type_name -> hearthstore.exportformat.Property
	4,  // 9: hearthstore.exportformat.EntityProto.raw_property:type_name -> hearthstore.exportformat.Property
	5,  // 10: hearthstore.exportformat.EntityProto.entity_group:type_name -> hearthstore.exportformat.Path
	0,  // 11: hearthstore.exportformat.EntitySetSpec.kind_type:type_name -> hearthstore.exportformat.KindType
	1,  // 12: hearthstore.exportformat.EntitySetSpec.namespace_type:type_name -> hearthstore.exportformat.NamespaceType
	8,  // 13: hearthstore.exportformat.SingleExportMetadataPointer.entity_set_spec:type_name -> hearthstore.exportformat.EntitySetSpec
	9,  // 14: hearthstore.exportformat.OverallExportMetadata.entity_set:type_name -> hearthstore.exportformat.SingleExportMetadataPointer
	11, // 15: hearthstore.exportformat.Backup.backup_info:type_name -> hearthstore.exportformat.BackupInfo
	12, // 16: hearthstore.exportformat.Backup.kind:type_name -> hearthstore.exportformat.KindBackupInfo
	17, // 17: hearthstore.exportformat.PropertyValue.ReferenceValue.pathelement:type_name -> hearthstore.exportformat.PropertyValue.ReferenceValue.PathElement
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_internal_exportformat_export_proto_init() }
func file_internal_exportformat_export_proto_init() {
	if File_internal_exportformat_export_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_exportformat_export_proto_rawDesc), len(file_internal_exportformat_export_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_exportformat_export_proto_goTypes,
		DependencyIndexes: file_internal_exportformat_export_proto_depIdxs,
		EnumInfos:         file_internal_exportformat_export_proto_enumTypes,
		MessageInfos:      file_internal_exportformat_export_proto_msgTypes,
	}.Build()
	File_internal_exportformat_export_proto = out.File
	file_internal_exportformat_export_proto_goTypes = nil
	file_internal_exportformat_export_proto_depIdxs = nil
}
