package server

import (
	"context"
	"testing"

	"google.golang.org/grpc/codes"

	firestorepb "cloud.google.com/go/firestore/apiv1/firestorepb"
)

func TestCreateDocument_Success(t *testing.T) {
	s := newTestServer(t)
	ctx := context.Background()

	doc, err := s.CreateDocument(ctx, &firestorepb.CreateDocumentRequest{
		Parent:       collectionParent(),
		CollectionId: "widgets",
		DocumentId:   "w1",
		Document: &firestorepb.Document{
			Fields: map[string]*firestorepb.Value{
				"color": strVal("red"),
				"count": intVal(5),
			},
		},
	})
	if err != nil {
		t.Fatalf("CreateDocument: %v", err)
	}
	if doc.Name != docName("widgets", "w1") {
		t.Errorf("Name = %q, want %q", doc.Name, docName("widgets", "w1"))
	}
	if doc.CreateTime == nil {
		t.Error("CreateTime should be set")
	}
	if doc.UpdateTime == nil {
		t.Error("UpdateTime should be set")
	}
}

func TestCreateDocument_AlreadyExists(t *testing.T) {
	s := newTestServer(t)
	ctx := context.Background()

	req := &firestorepb.CreateDocumentRequest{
		Parent:       collectionParent(),
		CollectionId: "widgets",
		DocumentId:   "w1",
		Document:     &firestorepb.Document{Fields: map[string]*firestorepb.Value{"color": strVal("red")}},
	}

	if _, err := s.CreateDocument(ctx, req); err != nil {
		t.Fatalf("first CreateDocument: %v", err)
	}
	_, err := s.CreateDocument(ctx, req)
	mustCode(t, err, codes.AlreadyExists)
}

func TestCreateDocument_AutoGeneratedID(t *testing.T) {
	s := newTestServer(t)
	ctx := context.Background()

	// Empty DocumentId means the server generates one.
	doc, err := s.CreateDocument(ctx, &firestorepb.CreateDocumentRequest{
		Parent:       collectionParent(),
		CollectionId: "widgets",
		Document:     &firestorepb.Document{Fields: map[string]*firestorepb.Value{"foo": strVal("bar")}},
	})
	if err != nil {
		t.Fatalf("CreateDocument: %v", err)
	}
	if doc.Name == "" {
		t.Error("expected non-empty document Name for auto-generated ID")
	}
}

func TestCreateDocument_FieldsPersistedCorrectly(t *testing.T) {
	s := newTestServer(t)
	ctx := context.Background()

	fields := map[string]*firestorepb.Value{
		"str":  strVal("hello"),
		"num":  intVal(99),
		"flag": boolVal(true),
	}
	_, err := s.CreateDocument(ctx, &firestorepb.CreateDocumentRequest{
		Parent:       collectionParent(),
		CollectionId: "widgets",
		DocumentId:   "w2",
		Document:     &firestorepb.Document{Fields: fields},
	})
	if err != nil {
		t.Fatalf("CreateDocument: %v", err)
	}

	got, err := s.GetDocument(ctx, &firestorepb.GetDocumentRequest{Name: docName("widgets", "w2")})
	if err != nil {
		t.Fatalf("GetDocument: %v", err)
	}
	if got.Fields["str"].GetStringValue() != "hello" {
		t.Errorf("str = %q, want %q", got.Fields["str"].GetStringValue(), "hello")
	}
	if got.Fields["num"].GetIntegerValue() != 99 {
		t.Errorf("num = %d, want 99", got.Fields["num"].GetIntegerValue())
	}
	if !got.Fields["flag"].GetBooleanValue() {
		t.Error("flag should be true")
	}
}
